using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace unlightvbe_kai_core.Enum
{
    public enum SkillCommandType
    {
        None = 0,
        AtkingLineLight,
        AtkingTurnOnOff,
        AtkingLineLightAnother,
        AtkingTurnOnOffAnother,
        AtkingStartPlay,
        AtkingStartPlayAnimate,
        BattleTurnControl,
        BattleSendMessage,
        BattleStartDice,
        AtkingInformationRecord,
        EventPlayerAllActionOff,
        EventActiveAIScore,
        BattleMoveControl,
        EventMoveActionOff,
        PersonMoveControl,
        PersonMoveActionChange,
        PersonAttackFirstControl,
        EventTotalDiceChange,
        EventPersonAbilityDiceChange,
        PersonTotalDiceControl,
        AtkingTrueDiceControl,
        PersonBloodControl,
        EventBloodActionOff,
        EventBloodActionChange,
        EventBloodReflection,
        EventHPLActionOff,
        EventHPLActionChange,
        EventHPLReflection,
        PersonAtkingOff,
        PersonPassiveOff,
        PersonAtkingOffSelect,
        PersonPassiveOffSelect,
        PersonAtkingInvalid,
        PersonResurrect,
        EventPersonResurrectActionOff,
        PersonChangeBattleImage,
        AtkingSeizeEnemyCards,
        EventAtkingSeizeEnemyCardsActionOff,
        AtkingDrawCards,
        EventAtkingDrawCardsActionOff,
        EventAtkingDrawCardsAddOnce,
        EventAtkingDrawCardsContinue,
        BattleDeckShuffle,
        AtkingDestroyCards,
        EventAtkingDestroyCardsActionOff,
        AtkingGiveCards,
        EventAtkingGiveCardsActionOff,
        AtkingGetUsedCards,
        EventAtkingGetUsedCardsActionOff,
        AtkingOneSelfCardControl,
        EventAtkingOneSelfCardControlActionOff,
        PersonMaxCardsNumControl,
        BattleInsertEventCard,
        PersonAddActualStatus,
        EventAddActualStatusData,
        ActualStatusEnd,
        PersonRemoveActualStatus,
        EventRemoveActualStatusActionOff,
        PersonAddBuff,
        BuffTurnEnd,
        PersonRemoveBuffAll,
        PersonRemoveBuffSelect,
        PersonBuffTurnChange,
        EventRemoveBuffActionOff
    }
}
